package com.nethermole.roborally.gamepackage.board.element;

public enum ElementEnum {

    BOARD_NAME,
    PIT,

    BEACON,
    BEACON0,
    BEACON1,

    CHECKPOINT1,
    CHECKPOINT2,
    CHECKPOINT3,

    GEAR_C,
    GEAR_CC,

    WALL_UP,
    WALL_RIGHT,
    WALL_DOWN,
    WALL_LEFT,

    LASER_H,
    LASER_V,

    //below are calculated from metadata
    WRENCH_1,
    WRENCH_2,

    CONVEYOR_1_UP_RIGHT,
    CONVEYOR_1_UP_DOWN,
    CONVEYOR_1_UP_LEFT,
    CONVEYOR_1_RIGHT_DOWN,
    CONVEYOR_1_RIGHT_LEFT,
    CONVEYOR_1_RIGHT_UP,
    CONVEYOR_1_DOWN_LEFT,
    CONVEYOR_1_DOWN_UP,
    CONVEYOR_1_DOWN_RIGHT,
    CONVEYOR_1_LEFT_UP,

    CONVEYOR_1_LEFT_RIGHT,
    CONVEYOR_1_LEFT_DOWN,
    CONVEYOR_2_UP_RIGHT,
    CONVEYOR_2_UP_DOWN,
    CONVEYOR_2_UP_LEFT,
    CONVEYOR_2_RIGHT_DOWN,
    CONVEYOR_2_RIGHT_LEFT,
    CONVEYOR_2_RIGHT_UP,
    CONVEYOR_2_DOWN_LEFT,
    CONVEYOR_2_DOWN_UP,
    CONVEYOR_2_DOWN_RIGHT,
    CONVEYOR_2_LEFT_UP,
    CONVEYOR_2_LEFT_RIGHT,
    CONVEYOR_2_LEFT_DOWN,

    CONVEYOR_3_UP_RIGHT,
    CONVEYOR_3_UP_DOWN,
    CONVEYOR_3_UP_LEFT,
    CONVEYOR_3_RIGHT_DOWN,
    CONVEYOR_3_RIGHT_LEFT,
    CONVEYOR_3_RIGHT_UP,
    CONVEYOR_3_DOWN_LEFT,
    CONVEYOR_3_DOWN_UP,
    CONVEYOR_3_DOWN_RIGHT,
    CONVEYOR_3_LEFT_UP,
    CONVEYOR_3_LEFT_RIGHT,
    CONVEYOR_3_LEFT_DOWN,
}
